services:
  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
    environment:
      JAVA_OPTS: "-XX:+UseZGC"
    init: true

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: >
      sh -c "
      ollama serve & 
      sleep 5 &&
      ollama pull nomic-embed-text &&
      ollama pull deepseek-r1:7b &&
      tail -f /dev/null
      "

  weaviate:
    depends_on:
      - ollama
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.1
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
      - weaviate_backups:/backups
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      BACKUP_FILESYSTEM_PATH: "/backups"
      ENABLE_MODULES: "text2vec-ollama,generative-ollama"
      ENABLE_API_BASED_MODULES: "true"
      CLUSTER_HOSTNAME: "node1"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: "user-a-key,user-b-key"
      AUTHENTICATION_APIKEY_USERS: "user-a,user-b"
      AUTHORIZATION_ENABLE_RBAC: "true"
      AUTHORIZATION_RBAC_ROOT_USERS: "user-a"

volumes:
  weaviate_data:
  weaviate_backups:
  ollama_models: